version: '3'
services:
    web:
        build:
            context: .
            dockerfile: etc/docker/nginx.Dockerfile
        volumes:
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        ports:
            - "8000:80"
            - "8001:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        depends_on:
            - php
            - mysql
    composer:
        image: "composer"
        volumes:
            - "./web/app/composer.json:/app/composer.json"
            - "./web/app/composer.lock:/app/composer.lock"
            - vendor:/app/vendor
        command: install --ignore-platform-reqs
    php:
        build:
            context: .
            dockerfile: etc/docker/php.Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
        container_name: php
        env_file:
            - ".env"
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
            - vendor:/var/www/html/app/vendor
        depends_on:
            - mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8002:80"
        environment:
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysql
    mysql:
        build:
            context: .
            dockerfile: etc/docker/mysql.Dockerfile
            args:
                - MYSQL_VERSION=${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"

volumes:
    vendor: